#### numpy conti..

In [1]:
import numpy as np

#### numpy methods:
        - dir(data type)

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
print(len(dir(np)))

608


#### zeros:
        - np.zeros(size)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

##### ones:
        np.ones(size)

In [8]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [9]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### full():
        - np.full(size,element)

In [10]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
np.full(5,"np")

array(['np', 'np', 'np', 'np', 'np'], dtype='<U2')

In [12]:
np.full((3,4),20)

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

##### linspace():
    - np.linspace(start range,end range,no of equal partitions)

In [13]:
np.linspace(1,15,6)

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])

In [14]:
np.linspace(1,20,8)

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

##### arange--->array range
        - syntax:
                - np.arange(start_range,end_range+1,step_value)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(50,101)

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [17]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [18]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

##### 2-d Array:
    - it is a combination of more than one 1-d array
    - syntax:
        np.array([[e1,e2,e3,e4],[e1,e2,e3,e4]])

In [21]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(type(b))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


##### Array attributes:
        - np.ndim
        - np.size
        - np.shape
        - np.dtype
        - np.nbytes
        - np.itemsize

In [28]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

2
8
(2, 4)
int32
4
32


##### how to access elements in 2-d array:
            - row index
            - column index

In [30]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
b[0]

array([1, 2, 3, 4])

In [32]:
b[1]

array([5, 6, 7, 8])

In [ ]:
# row index,col index

In [33]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
b[0]

array([1, 2, 3, 4])

In [35]:
b[0,2]

3

In [ ]:
6

In [37]:
b[1,1]

6

In [38]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
2,6

(2, 6)

In [44]:
b[0:4,1]

array([2, 6])

In [46]:
b[:,1]

array([2, 6])

In [47]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
2 3
6 7

In [51]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

In [52]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
1 4
5 8

In [57]:
b[:,0:4:3]

array([[1, 4],
       [5, 8]])

In [58]:
b[:,::3]

array([[1, 4],
       [5, 8]])

##### 3-d Array:
    - it is a combination of more than one 2-d arrays
    - syntax:
        np.array([[[e1,e2,e3,e4],[e1,e2,e3,e4]],[[e1,e2,e3,e4],[e1,e2,e3,e4]]])

In [60]:
c=np.array([[[1,2,3,4],[5,6,7,8]],[[9,7,6,5],[1,3,5,9]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

In [61]:
print(c.ndim)
print(c.shape)
print(c.size)
print(c.itemsize)
print(c.nbytes)
print(c.dtype)

3
(2, 2, 4)
16
4
64
int32


#### how to access elements in 3-d array:
        - array index
        - row index
        - col index

In [62]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

In [63]:
c[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
c[1]

array([[9, 7, 6, 5],
       [1, 3, 5, 9]])

In [66]:
# rows->1:
c[0,0]

array([1, 2, 3, 4])

In [67]:
c[0,1]

array([5, 6, 7, 8])

In [68]:
# rows->2
c[1]

array([[9, 7, 6, 5],
       [1, 3, 5, 9]])

In [69]:
c[1,0]

array([9, 7, 6, 5])

In [70]:
c[1,1]

array([1, 3, 5, 9])

In [71]:
# element index
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

In [72]:
c[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
c[0,1]

array([5, 6, 7, 8])

In [74]:
c[0,1,1]

6

In [75]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

In [76]:
c[1]

array([[9, 7, 6, 5],
       [1, 3, 5, 9]])

In [77]:
c[1,1]

array([1, 3, 5, 9])

In [78]:
c[1,1,3]

9

In [79]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

In [ ]:
4,5

In [81]:
c[:,0]

array([[1, 2, 3, 4],
       [9, 7, 6, 5]])

In [83]:
c[:,0,3]

array([4, 5])

In [84]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

 2 3
 7 6

In [85]:
c[:]

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

In [86]:
c[:,0]

array([[1, 2, 3, 4],
       [9, 7, 6, 5]])

In [87]:
c[:,0,1:3]

array([[2, 3],
       [7, 6]])

In [88]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 7, 6, 5],
        [1, 3, 5, 9]]])

1 4
5 8


9 5
1 9

In [95]:
c[:,:,0:4:2]

array([[[1, 3],
        [5, 7]],

       [[9, 6],
        [1, 5]]])

In [93]:
c[:,:,::3]

array([[[1, 4],
        [5, 8]],

       [[9, 5],
        [1, 9]]])