#### Numpy Conti..

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

##### Reshape:
    - it creates new shape of  an original array
    - syntax:
        np.reshape(row size,column size)---->2-d array
        np.reshape(array size,row size,column size)--->3-d array

In [5]:
# 1-d array
a=np.arange(10)
print(a)
print(a.size)

[0 1 2 3 4 5 6 7 8 9]
10


In [9]:
# 2-d array
a1=a.reshape(5,2)
a1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
# 3-d array
a2=a.reshape(2,5,1)
a2

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [15]:
# 1-d array
b=np.arange(36)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [16]:
b.size

36

In [21]:
# 2-d
b1=b.reshape(6,6)
b1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [22]:
# 3-d
b2=b.reshape(3,4,3)
b2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

#### Array concatenation:
        - np.concatenate((array1,array2))

In [28]:
# 1-d
array1=np.arange(1,11)
print(array1)
print(array1.size)
array2=np.arange(11,21)
print(array2)
print(array2.size)

# result
res=np.concatenate((array1,array2))
print(res)

[ 1  2  3  4  5  6  7  8  9 10]
10
[11 12 13 14 15 16 17 18 19 20]
10
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [31]:
# 2-d
x=array1.reshape(5,2)
print(x)
x1=array2.reshape(5,2)
print(x1)

# result
res1=np.concatenate((x,x1))
print(res1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [34]:
# 3-d
x2=array1.reshape(2,5,1)
print(x2)
x3=array2.reshape(2,5,1)
print(x3)

# result
res2=np.concatenate((x2,x3))
print(res2)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
[[[11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]]]


#### Statistical and Mathematical operations on numpy

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# min()
np.min(a)

0

In [37]:
# max()
np.max(a)

9

In [38]:
# argmin()
np.argmin(a)

0

In [39]:
# argmax()
np.argmax(a)

9

In [40]:
np.sum(a)

45

In [41]:
# mean
np.mean(a)

4.5

In [42]:
# median
np.median(a)

4.5

In [44]:
# var
np.var(a)

8.25

In [45]:
# stdev
np.std(a)

2.8722813232690143

In [46]:
# pi
np.pi

3.141592653589793

In [47]:
# exp
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [48]:
# pow
np.power(a,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [49]:
np.power(a,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [51]:
# remaindar
np.remainder(a,4)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1], dtype=int32)

In [54]:
# modulo
np.mod(a,4)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1], dtype=int32)

In [59]:
# multiply
np.multiply(a,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
np.multiply(a,23)

array([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207])

In [61]:
# sin(),cos(),tan()
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [62]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [63]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [64]:
np.sin(a)/np.cos(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [65]:
np.cos(a)/np.sin(a)

C:\Users\win\AppData\Local\Temp\ipykernel_5200\3202920359.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.cos(a)/np.sin(a)


array([        inf,  0.64209262, -0.45765755, -7.01525255,  0.86369115,
       -0.29581292, -3.436353  ,  1.14751542, -0.14706506, -2.21084541])

In [66]:
# log(),log2(),log10()
np.log(a)

C:\Users\win\AppData\Local\Temp\ipykernel_5200\592015992.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [67]:
np.log2(a)

C:\Users\win\AppData\Local\Temp\ipykernel_5200\2088242240.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(a)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [68]:
np.log10(a)

C:\Users\win\AppData\Local\Temp\ipykernel_5200\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [69]:
### row sum(),column sum()
print(a1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [71]:
np.sum(a1,1) # row sum

array([ 1,  5,  9, 13, 17])

In [72]:
np.sum(a1,0) # column sum

array([20, 25])

In [73]:
#### complex numbers
c=np.array([2+7j,5+8j,9+3j])
c

array([2.+7.j, 5.+8.j, 9.+3.j])

In [76]:
np.real(c)

array([2., 5., 9.])

In [80]:
np.imag(c)

array([7., 8., 3.])

##### stacking:
        - it arranges array elements in appropriate way
        - types of stacking:
                - horizontal stacking
                        - np.hstack()
                - vertical stacking
                        - np.vstack()

In [81]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.vstack(s)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [83]:
np.hstack(s)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis.
    s

In [86]:
s1= np.array([[1],[2],[3]])
s2= np.array([[4],[5],[6]])
np.hstack((s1,s2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
np.vstack((s1,s2))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [88]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    concatenate : Join a sequence of arrays along an existing axis

#### Random Methods:
        - np.random.randint
        - np.random.randn
        - np.random.rand

In [93]:
np.random.randint(10)

3

In [96]:
np.random.randint(21,35,size=5)

array([24, 22, 28, 24, 26])

In [99]:
np.random.randint(1,50,size=(4,5))

array([[23, 15, 15, 47, 38],
       [36, 37, 22,  3, 27],
       [38, 27, 31, 20, 40],
       [36, 31, 26, 18, 46]])

In [104]:
### rand
np.random.rand()

0.5699679419114847

In [105]:
np.random.rand(5)

array([0.89091984, 0.71682493, 0.39913162, 0.58697821, 0.71583968])

In [106]:
# randn--->normal distribution values
np.random.randn()

-0.9889563436641863

In [107]:
np.random.randn(5)

array([ 0.17848003, -1.52611793, -1.52743386, -0.61181158,  0.95813464])

In [108]:
np.random.randn(10)

array([ 1.95438579, -1.9217178 , -1.18553536, -0.1585719 ,  0.01924996,
       -0.69605704,  2.30100347,  0.71535517,  1.24725359, -2.28249504])

##### ravel():
        - ravel is a one of the function in numpy which is used to copy the data from one array
    into another array.if any changes made in duplicate array those changes are applied into original array


##### flatten():
        - ravel is a one of the function in numpy which is used to copy the data from one array
    into another array.if any changes made in duplicate array those changes are not applied into original array

In [109]:
original=np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
copy=original.ravel()
copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
copy[5]=500

In [113]:
copy

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9])

In [114]:
original

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9])

In [115]:
# flatten()
original1=np.arange(11,21)
original1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [117]:
copy1=original1.flatten()
copy1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [119]:
copy1[8]=900

In [120]:
copy1

array([ 11,  12,  13,  14,  15,  16,  17,  18, 900,  20])

In [121]:
original1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])