##### numpy:
       - numpy stands for numerical python
       - by using numpy library we can create multi dimensional arrays in python
       - the default dimension size of numpy is 32.

##### library installation:
        - pip install library name or package name
                ex: pip install numpy


##### libary usage:
        - import numpy

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

#### how to create an array by using numpy:
            np.array([e1,e2,e3,e4,...en])

In [6]:
a=np.array([23,34,45,56,67,78,89,90])
a

array([23, 34, 45, 56, 67, 78, 89, 90])

In [7]:
type(a)

numpy.ndarray

##### how to access an array elements:
        - index
                - array_variable[index_position]
                    - +ve index
                            left to right(0,1,2....n)
                    - - ve index
                            right to left(-1,-2,-3....)
        - slicing
               - syntax:
                       array_variable[start_index:end_index+1:step_value]

In [12]:
#### index:0
print(a)
print(a[3])
print(a[7])
print(a[-1])
print(a[-3])

[23 34 45 56 67 78 89 90]
56
90
90
78


In [37]:
# slicing
print(a)
print(a[0:8:1])
print(a[0:4])
print(a[:4])
print(a[4:8])
print(a[4:])
# reverse()
print(a[-1:-9:-1])
print(a[::-1])
print(a[0:8:2])
print(a[::2])
print(a[-1:-9:-2])
print(a[::-2])




[23 34 45 56 67 78 89 90]
[23 34 45 56 67 78 89 90]
[23 34 45 56]
[23 34 45 56]
[67 78 89 90]
[67 78 89 90]
[90 89 78 67 56 45 34 23]
[90 89 78 67 56 45 34 23]
[23 45 67 89]
[23 45 67 89]
[90 78 56 34]
[90 78 56 34]


In [ ]:
90 78 56 34